In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
class Model(nn.Module): #inherit nn.module class , base class
    def __init__(self,num_features):
      super().__init__() #inherit from parent class super is used
      self.linear = nn.Linear(num_features,1)
      self.sigmoid = nn.Sigmoid()

    def forward(self,features):
      out = self.linear(features) #wx+b
      out = self.sigmoid(out) #sig(z)
      return out

In [ ]:
#create a DS
features = torch.rand(10,5) #5 features = col
Model = Model(features.shape[1])

Model(features) #recommended syntax
#model.forward(features) can work but not recommended


#we get forward pass of all 10

tensor([[0.3546],
        [0.4389],
        [0.3820],
        [0.3879],
        [0.3831],
        [0.4329],
        [0.4145],
        [0.4068],
        [0.4145],
        [0.3943]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
Model.linear.weight
#5 weights

Parameter containing:
tensor([[-0.3194,  0.0560, -0.3101, -0.0557, -0.0543]], requires_grad=True)

In [ ]:
Model.linear.bias

Parameter containing:
tensor([-0.0025], requires_grad=True)

In [ ]:
#if we want to visulaize
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [ ]:
from torchinfo import summary
summary(Model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

<h1> HL NN 5 Input, 3 Neuron in HL, 1 output Neuron </h1>

In [ ]:
class Model(nn.Module): #inherit nn.module class , base class
    def __init__(self,num_features):
      super().__init__() #inherit from parent class super is used
      self.linear1 = nn.Linear(num_features,3)
      self.relu = nn.ReLU()
      self.linear2 = nn.Linear(3,1)
      self.sigmoid = nn.Sigmoid()

    def forward(self,features):
      out = self.linear1(features) #wx+b
      out = self.relu(out) #sig(z)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out

In [ ]:
features = torch.rand(10,5) #5 features = col
Model = Model(features.shape[1])

Model(features) #recommended syntax

tensor([[0.3643],
        [0.3644],
        [0.3663],
        [0.3655],
        [0.3555],
        [0.3782],
        [0.3806],
        [0.3645],
        [0.3536],
        [0.3810]], grad_fn=<SigmoidBackward0>)

In [ ]:
Model.linear1.weight

Parameter containing:
tensor([[ 0.0574,  0.0426,  0.0041, -0.2887, -0.0447],
        [ 0.2772, -0.1835,  0.1835,  0.3708, -0.3087],
        [-0.2656,  0.1684,  0.4349, -0.2523, -0.0303]], requires_grad=True)

In [ ]:
Model.linear2.bias

Parameter containing:
tensor([-0.4152], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(Model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

<h2> Sequential Container </h2>

In [ ]:
class Model(nn.Module): #inherit nn.module class , base class
    def __init__(self,num_features):
      super().__init__() #inherit from parent class super is used
      self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
      )

    def forward(self,features):
      out = self.network(features)
      return out

In [ ]:
features = torch.rand(10,5) #5 features = col
Model = Model(features.shape[1])

Model(features)

tensor([[0.3853],
        [0.3738],
        [0.4168],
        [0.3565],
        [0.3887],
        [0.3755],
        [0.3779],
        [0.3955],
        [0.3763],
        [0.3611]], grad_fn=<SigmoidBackward0>)

<h1> Change in pipeline code </h1>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
#test train split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
#

In [ ]:
#label encoding
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [ ]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
learning_rate = 0.1
epochs = 50

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [ ]:
model = MySimpleNN(x_train_tensor.shape[1])

In [ ]:
optimizer= torch.optim.SGD(model.parameters(),lr=learning_rate)
#model.parameters

In [ ]:
#create Model

#define loop
for epoch in range(epochs):
  #forward Pass
  y_pred = model(x_train_tensor)
  #print(y_pred)

  #loss calculate
  loss = loss_function(y_pred,y_train_tensor.view(-1,1)) #reshape data
  #print(loss)

  #prevent accumulation of gradient recommended to be before backward
  optimizer.zero_grad()

  #backward Pass

  loss.backward()
  #weight parameter update
  optimizer.step()


  #priint losss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.133743554353714
Epoch: 2, Loss: 0.13281340897083282
Epoch: 3, Loss: 0.13191023468971252
Epoch: 4, Loss: 0.131032794713974
Epoch: 5, Loss: 0.13017986714839935
Epoch: 6, Loss: 0.12935039401054382
Epoch: 7, Loss: 0.12854333221912384
Epoch: 8, Loss: 0.12775766849517822
Epoch: 9, Loss: 0.12699249386787415
Epoch: 10, Loss: 0.12624697387218475
Epoch: 11, Loss: 0.125520259141922
Epoch: 12, Loss: 0.12481161952018738
Epoch: 13, Loss: 0.12412028014659882
Epoch: 14, Loss: 0.12344559282064438
Epoch: 15, Loss: 0.12278688699007034
Epoch: 16, Loss: 0.12214354425668716
Epoch: 17, Loss: 0.12151501327753067
Epoch: 18, Loss: 0.1209006980061531
Epoch: 19, Loss: 0.12030010670423508
Epoch: 20, Loss: 0.11971274763345718
Epoch: 21, Loss: 0.11913809925317764
Epoch: 22, Loss: 0.11857577413320541
Epoch: 23, Loss: 0.1180252730846405
Epoch: 24, Loss: 0.11748626083135605
Epoch: 25, Loss: 0.11695831269025803
Epoch: 26, Loss: 0.11644107103347778
Epoch: 27, Loss: 0.11593414843082428
Epoch: 28, Loss: 0.11543724685907364
Epoch: 29, Loss: 0.1149500235915184
Epoch: 30, Loss: 0.11447219550609589
Epoch: 31, Loss: 0.11400343477725983
Epoch: 32, Loss: 0.11354347318410873
Epoch: 33, Loss: 0.11309204995632172
Epoch: 34, Loss: 0.11264889687299728
Epoch: 35, Loss: 0.11221377551555634
Epoch: 36, Loss: 0.11178641766309738
Epoch: 37, Loss: 0.1113666296005249
Epoch: 38, Loss: 0.1109541803598404
Epoch: 39, Loss: 0.11054886877536774
Epoch: 40, Loss: 0.11015047878026962
Epoch: 41, Loss: 0.10975882411003113
Epoch: 42, Loss: 0.10937372595071793
Epoch: 43, Loss: 0.10899500548839569
Epoch: 44, Loss: 0.1086224615573883
Epoch: 45, Loss: 0.10825596004724503
Epoch: 46, Loss: 0.10789531469345093
Epoch: 47, Loss: 0.10754039883613586
Epoch: 48, Loss: 0.1071910485625267
Epoch: 49, Loss: 0.1068471223115921
Epoch: 50, Loss: 0.10650847852230072

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.4323,  0.3088,  0.3629,  0.3120,  0.1595,  0.2650,  0.2551,  0.4363,
          0.0406, -0.1325,  0.3689, -0.0213,  0.2447,  0.3086, -0.0373, -0.2651,
         -0.1522,  0.1653, -0.1530, -0.0480,  0.4117,  0.5475,  0.2463,  0.5336,
          0.1872,  0.3245,  0.3435,  0.3252,  0.4431, -0.0626]],
       requires_grad=True)

In [ ]:
 #model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()# prob to label
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

print(y_pred)

Accuracy: 0.5258541107177734
tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.]])